title: Andrey Glauzer | Analista de Suporte / Analista de Segurança da Informação em Barueri/SP
description: "Um blog sobre coisas novas que estou aprendendo."
url: "https://andreyglauzer.com"
author:
  name: "Andrey Glauzer"
  email: "nglauzer@gmail.com"
  url: "https://andreyglauzer.com"