# Configurações do Site.
title: Andrey Glauzer | Analista de Suporte / Analista de Segurança da Informação em Barueri/SP
description: "Um blog sobre coisas novas que estou aprendendo ou interessado, e para fixar tudo que estou praticando."
url: ""
author:
  name: "Andrey Glauzer"
  email: "nglauzer@gmail.com"

# Analise de Dados Quantcast
ID: p-BTQDD6C697r5P

# Configurações da Build

baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /:num/

# Convigurações Padrões
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins que eu utilizo
gems:
  - jekyll-paginate

# Versão do site.
version: "1.1.0"

# Projetos
projetos:
  - nome: andreyglauzer.com
    imagem: andreyglauzer.png
    descricao: Meu blog pessoal, desenvolvido com GitHub Pages, com a ajuda o Jekyll <3.
    url: https://github.com/andreyglauzer/andreyglauzer.github.io
    data: Janeiro de 2016
    invert: true

  - nome: Cortexiphan
    imagem: cortexiphan.png
    descricao: Projeto desenvolvido em Python, que faz coleta no youtube, juntando informações de canais e playlists de cursos focados na área de T.I
    url: https://github.com/andreyglauzer/cortexiphan
    data: Agosto de 2017

  - nome: pybook
    imagem: pybook.png
    descricao: Projeto escrito em Python, que coleta o maximo de informações de outros sites, com base nos livros mais lidos do site Skoob, coletando como link para download do arquivo, descrição Livro/Autor, menor preço etc..
    url: https://github.com/andreyglauzer/pybook
    data: Setembro de 2016
    invert: true

  - nome: Alidoces Oficial
    imagem: alidoces.png
    descricao: Projeto desenvolvido para um amigo, para o mesmo poder divulgar o trabalho que sua esposa faz de venda de bolos no pote, e bolos sobre encomendas.
    url: https://alidocesoficial.com
    data: Janeiro de 2017