# Configurações do Site.
title: Andrey Glauzer | Analista de Suporte / Analista de Segurança da Informação em Barueri/SP
description: "Um blog sobre coisas novas que estou aprendendo ou interessado, e para fixar tudo que estou praticando."
url: ""
author:
  name: "Andrey Glauzer"
  email: "nglauzer@gmail.com"

# Analise de Dados Quantcast
ID: p-BTQDD6C697r5P

# Configurações da Build

baseurl: "/"
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /:num/

# Convigurações Padrões
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins que eu utilizo
gems:
  - jekyll-paginate

# Versão do site.
version: "1.1.0"

# Projetos
projetos:
  - nome: andreyglauzer.com
    imagem: andreyglauzer.png
    descricao: Meu blog pessoal, desenvolvido com GitHub Pages, com a ajuda o Jekyll <3.
    url: https://github.com/andreyglauzer/andreyglauzer.github.io
    data: Janeiro de 2016
    invert: true

  - nome: Cortexiphan
    imagem: cortexiphan.png
    descricao: Projeto desenvolvido em Python, que faz coleta no youtube, juntando informações de canais e playlists de cursos focados na área de T.I
    url: https://github.com/andreyglauzer/cortexiphan
    data: Agosto de 2017

  - nome: pybook
    imagem: pybook.png
    descricao: Projeto escrito em Python, que coleta o maximo de informações de outros sites, com base nos livros mais lidos do site Skoob, coletando como link para download do arquivo, descrição Livro/Autor, menor preço etc..
    url: https://github.com/andreyglauzer/pybook
    data: Setembro de 2016
    invert: true

  - nome: Alidoces Oficial
    imagem: alidoces.png
    descricao: Projeto desenvolvido para um amigo, para o mesmo poder divulgar o trabalho que sua esposa faz de venda de bolos no pote, e bolos sobre encomendas.
    url: https://alidocesoficial.com
    data: Janeiro de 2017


collections:
    sonicwall:
        output: true
        permalink: /colecoes/sonicwall/:path/
    pfsense:
        output: true
        permalink: /colecoes/pfsense/:path/
    windowsserver:
        output: true
        permalink: /colecoes/windowsserver/:path/
    linux:
        output: true
        permalink: /colecoes/linux/:path/
        

infocolecoes:
  - sonicwall:
    titulo: SonicWall
    descricao: Um pouco mais sobre novas coisas que estou aprendendo sobre o SonicWall, e sistuações que venho enfrentando.
    img: /img/collections/sonicwall.jpg
    permalink: /colecoes/sonicwall
  - pfsense:
    titulo: pfSense
    descricao: Configurações e procedimentos referente ao pfSense, e soluções que já apresentei em algumas empresas.
    img: /img/collections/pfsense.jpg
    permalink: /colecoes/pfsense
  - windowsserver:
    titulo: Windows Server
    descricao: Administração, configuração e gerencimando de Servidores Windows, o melhor para trabalhar com client.
    img: /img/collections/windowsserver.jpg
    permalink: /colecoes/windowsserver
  - linux:
    titulo: Sistemas Linux
    descricao: Administração e configurações de Servidores/Desktops Linux, e sistuações que já enfrentei mediante ao mesmo.
    img: /img/collections/linux.jpg
    permalink: /colecoes/linux