# Informações gerais

title: Andrey Glauzer | Analista de Suporte / Analista de Segurança da Informação em Barueri/SP
description: "Um blog sobre coisas novas que estou aprendendo."
baseurl: ""
url: ""



# Configurações da Build
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed